### ISSUE TITLE
Big Issues

### ISSUE THREAD

**Issue by satyam8932** [nafets33/ozz#1]
Hi Stephen, I'm Satyam from Upwork as you posted the job and this repo and after analyzing your code I've seen that you have done hardcodings and also directly pasted your OPENAI API KEY which can get leaked and cost you also that's not a good practise.

I can help you with that if you want now how to use API KEY securely 😄 

Thanks

**Comment by nafets33** [comment]
Thanks yea that’s an old key and doesn’t work.

I use os.environ

Do you think you can help me find a voice?

**Comment by satyam8932** [comment]
Yes of course and i can also create your app completely in a good manner

**Comment by satyam8932** [comment]
well instead of os.environ u can simply use python-dotenv

**Comment by satyam8932** [comment]
Hello Stephen, What's going on? 
I messaged you on Upwork but you didn't respond well I have got the Voice that you need :)
Can you please respond to me back on Upwork so that we can get started?

**Comment by satyam8932** [comment]
Hi Stephen, I send you some voice examples of ai. Have you checked it as i'm waiting for your next move. Please give me a response through any medium so that i can prepare the setup :)

**Comment by satyam8932** [comment]
Thanks
